- name: group | backup
  group:
    name: backup
    gid: 994
    system: true

- name: user | backup
  user:
    name: backup
    comment: Backup user
    uid: 994
    group: backup
    system: true
    home: /var/local/backup

#- name: users | find old users
#  shell: "cut -d: -f1 /etc/group | grep '^backup-'"
#  changed_when: false
#  register: backup_users

#- debug: "{{ backup_users }}"

- name: syncthing | backup home directory
  file:
    path: /var/local/backup/syncthing
    owner: backup
    group: backup
    state: directory

- name: systemd | syncthing backup override directory
  file:
    path: /etc/systemd/system/syncthing@backup.service.d
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: systemd | syncthing backup override
  copy:
    src: etc/systemd/system/syncthing@backup.service.d/50-backup.conf
    dest: /etc/systemd/system/syncthing@backup.service.d/50-backup.conf
    owner: root
    group: root
    mode: '0644'
