- name: install OpenSSH
  pacman: name=openssh state=present

- name: firewall | install SSH dropin
  notify:
    - systemd | reload firewall
  template:
    src: etc/nftables.d/inet/input/50-ssh.conf.j2
    dest: /etc/nftables.d/inet/input/50-ssh.conf
    owner: root
    group: root
    mode: '0644'

- name: ssh | create dropin directory
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: ssh | base configuration file
  template:
    src: etc/ssh/sshd_config.d/00-base.j2
    dest: /etc/ssh/sshd_config.d/00-base
    owner: root
    group: root
    mode: '0644'

- name: ssh | assemble configuration file
  assemble:
    src: /etc/ssh/sshd_config.d/
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/bin/sshd -t -f %s

- name: systemd | create sshd.socket.d
  file: 
    path: /etc/systemd/system/sshd.socket.d
    state: directory

- name: systemd | install sshd.socket override
  notify:
    - systemd | restart sshd.socket
  template:
    src: etc/systemd/system/sshd.socket.d/50-port.conf.j2
    dest: /etc/systemd/system/sshd.socket.d/50-port.conf
    owner: root
    group: root
    mode: '0644'
    
- name: systemd | disable sshd.service
  service: name=sshd.service enabled=false state=stopped
  
- name: systemd | enable sshd.socket
  service: name=sshd.socket enabled=true state=started
