- name: pacman | install OpenSSH
  pacman: name=openssh state=present

- name: firewalld | check ssh-custom service
  stat:
    path: /etc/firewalld/services/ssh-custom.xml
  register: firewalld_service

- name: firewalld | copy ssh-custom service
  template:
    src: etc/firewalld/services/ssh-custom.xml.j2
    dest: /etc/firewalld/services/ssh-custom.xml
    owner: root
    group: root
    mode: '0644'

- name: firewalld | create ssh-custom service
  command: firewallctl new -p service -f /etc/firewalld/services/ssh-custom.xml
  when: not firewalld_service.stat.exists

- name: firewalld | enable ssh-custom service
  firewalld:
    service: ssh-custom
    permanent: true
    immediate: true
    state: enabled

- name: ssh | create dropin directory
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: ssh | base configuration file
  template:
    src: etc/ssh/sshd_config.d/00-base.j2
    dest: /etc/ssh/sshd_config.d/00-base
    owner: root
    group: root
    mode: '0644'

- name: ssh | assemble configuration file
  assemble:
    src: /etc/ssh/sshd_config.d/
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/bin/sshd -t -f %s

- name: systemd | create sshd.socket.d
  file: 
    path: /etc/systemd/system/sshd.socket.d
    state: directory

- name: systemd | install sshd.socket override
  notify:
    - systemd | restart sshd.socket
  template:
    src: etc/systemd/system/sshd.socket.d/50-port.conf.j2
    dest: /etc/systemd/system/sshd.socket.d/50-port.conf
    owner: root
    group: root
    mode: '0644'
    
- name: systemd | disable sshd.service
  service: name=sshd.service enabled=false state=stopped
  
- name: systemd | enable sshd.socket
  service: name=sshd.socket enabled=true state=started
  
- name: firewalld | disable ssh service
  firewalld:
    service: ssh
    permanent: true
    state: disabled
