- name: Create backup group
  group:
    name: backup
    gid: 994
    system: true

- name: Create backup user
  user:
    name: backup
    comment: Backup user
    uid: 994
    group: backup
    system: true
    
