- name: Synchronize NixOS config
  become: no
  synchronize:
    src: files/nixos/
    dest: /etc/nixos/
    rsync_path: rsync
    owner: no
    group: no
    delete: yes
    rsync_opts:
      - "--exclude=/configuration.nix"

- name: Create configuration symlink
  become: no
  file:
    src: machines/{{ inventory_hostname }}/configuration.nix
    dest: /etc/nixos/configuration.nix
    state: link

- name: Rebuild NixOS configuration
  command: nixos-rebuild switch -I nixos-config=/etc/nixos/configuration.nix -I localpkgs=/etc/nixos
  register: nixos_rebuild
  changed_when: nixos_rebuild.stderr is search("these derivations will be built")

