- name: worker directory
  file:
    path: "{{ aur_buildbot_worker_directory }}"
    state: directory
    owner: aur-buildbot-worker
    group: aur-buildbot-worker
    mode: "0750"
- name: worker info directory
  file:
    path: "{{ aur_buildbot_worker_directory }}/info"
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: worker host file
  template:
    src: base_dir/info/host
    dest: "{{ aur_buildbot_worker_directory }}/info/host"
    owner: root
    group: root
    mode: "0644"
- name: worker admin file
  template:
    src: base_dir/info/admin
    dest: "{{ aur_buildbot_worker_directory }}/info/admin"
    owner: root
    group: root
    mode: "0644"
