- name: pacman | install buildbot-worker and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - buildbot-worker
    - python-service-identity

- name: buildbot-worker | create base directory
  file:
    path: "{{ buildbot_worker_base_dir }}"
    state: directory

- name: group | {{ buildbot_worker_service_name }}-worker
  group:
    name: "{{ buildbot_worker_service_name }}-worker"
    system: true

- name: user | {{ buildbot_worker_service_name }}-worker
  user:
    name: "{{ buildbot_worker_service_name }}-worker"
    group: "{{ buildbot_worker_service_name }}-worker"
    shell: /usr/bin/nologin
    home: "{{ buildbot_worker_base_dir }}"
    system: true

- name: buildbot-worker | base directory permissions
  file:
    path: "/var/lib/{{ buildbot_worker_service_name }}/worker"
    state: directory
    owner: "{{ buildbot_worker_service_name }}-worker"
    group: "{{ buildbot_worker_service_name }}-worker"
    mode: '0750'

- name: buildbot-worker | create config directory
  file:
    path: /etc/{{ buildbot_worker_service_name }}/worker
    state: directory
    owner: root
    group: "{{ buildbot_worker_service_name }}-worker"
    mode: '0750'

- name: buildbot-worker | create worker config
  template:
    src: etc/buildbot/worker/buildbot.tac.j2
    dest: /etc/{{ buildbot_worker_service_name }}/worker/buildbot.tac
    owner: root
    group: "{{ buildbot_worker_service_name }}-worker"
    mode: '0640'
  notify:
    - systemd | restart buildbot-worker

- name: buildbot-worker | admin file
  notify:
    - systemd | restart buildbot-worker
  template:
    src: base_dir/info/admin.j2
    dest: "{{ buildbot_worker_base_dir }}/info/admin"

- name: buildbot-worker | host file
  notify:
    - systemd | restart buildbot-worker
  template:
    src: base_dir/info/host.j2
    dest: "{{ buildbot_worker_base_dir }}/info/host"
    
- name: systemd | install {{ buildbot_worker_service_name }}-worker.service
  notify:
    - systemd | restart buildbot-worker
  template:
    src: etc/systemd/system/buildbot-worker.service.j2
    dest: /etc/systemd/system/{{ buildbot_worker_service_name }}-worker.service
    owner: root
    group: root
    mode: 0644

- name: systemd | enable {{ buildbot_worker_service_name }}-worker.service
  service: name={{ buildbot_worker_service_name }}-worker.service enabled=true state=started daemon_reload=true
