- name: Create group
  group:
    name: "{{ item.0 }}"
    gid: "{{ item.1.gid | default(omit) }}"
  with_together: ["{{ args.groups.keys() }}", "{{ args.groups.values() }}"]

- name: Create user
  user:
    name: "{{ item.0 }}"
    uid: "{{ item.1.uid | default(omit) }}"
    group: "{{ item.1.group | default(omit) }}"
    groups: "{{ item.1.groups | default(omit) }}"
    comment: "{{ item.1.comment | default(omit) }}"
  with_together: ["{{ args.users.keys() }}", "{{ args.users.values() }}"]

- name: pacman | custom repository file
  copy:
    src: etc/pacman.d/custom.conf
    dest: /etc/pacman.d/custom.conf
    owner: root
    group: root
    mode: '0644'

- name: pacman | custom repository include
  lineinfile:
    path: /etc/pacman.conf
    insertafter: EOF
    line: "Include = /etc/pacman.d/custom.conf"
