- name: build home directory
  file:
    path: /var/lib/build
    state: directory
    owner: hydra-queue-runner
    group: hydra
    mode: '0750'
- name: build ssh directory
  file:
    path: /var/lib/build/.ssh
    state: directory
    owner: hydra-queue-runner
    group: hydra
    mode: '0755'
- name: build ssh private key
  copy:
    src: var/lib/build/.ssh/id_ed25519
    dest: /var/lib/build/.ssh/id_ed25519
    owner: hydra-queue-runner
    group: hydra
    mode: '0400'
- name: signing private key
  copy:
    src: etc/nix/signing-key.sec
    dest: /etc/nix/signing-key.sec
    owner: root
    group: root
    mode: '0600'
