- name: pacman | install buildbot and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - buildbot
    - python-service-identity

- name: buildbot | create base directory
  file:
    path: "{{ buildbot_base_dir }}"
    state: directory

- name: group | {{ buildbot_name }}
  group:
    name: "{{ buildbot_name }}"
    system: true

- name: user | {{ buildbot_name }}
  user:
    name: "{{ buildbot_name }}"
    group: "{{ buildbot_name }}"
    shell: /usr/bin/nologin
    home: "{{ buildbot_base_dir }}"
    system: true

- name: buildbot | base directory permissions
  file:
    path: "/var/lib/{{ buildbot_name }}/master"
    state: directory
    owner: "{{ buildbot_name }}"
    group: "{{ buildbot_name }}"
    mode: '0750'

- name: buildbot | create config directory
  file:
    path: /etc/{{ buildbot_name }}/master
    state: directory
    owner: root
    group: "{{ buildbot_name }}"
    mode: '0750'

- name: buildbot | config file
  notify:
    - systemd | reload buildbot
  template:
    src: "{{ buildbot_config_file }}"
    dest: /etc/{{ buildbot_name }}/master/master.cfg
    owner: root
    group: "{{ buildbot_name }}"
    mode: '0640'
    
- name: buildbot | twisted config file
  notify:
    - systemd | restart buildbot
  template:
    src: etc/buildbot/master/buildbot.tac.j2
    dest: /etc/{{ buildbot_name }}/master/buildbot.tac
    owner: root
    group: "{{ buildbot_name }}"
    mode: '0640'

- name: buildbot | create database
  become: yes
  become_user: "{{ buildbot_name }}"
  notify:
    - systemd | restart buildbot
  command: buildbot create-master {{ buildbot_base_dir | quote }}
  args:
    creates: "{{ buildbot_base_dir }}/state.sqlite"

- name: systemd | install {{ buildbot_name }}.service
  notify:
    - systemd | restart buildbot
  template:
    src: etc/systemd/system/buildbot.service.j2
    dest: /etc/systemd/system/{{ buildbot_name }}.service
    owner: root
    group: root
    mode: '0644'

- name: firewall | buildbot dropin
  notify:
    - reload firewall
  template:
    src: etc/nftables.d/inet/input/52-buildbot.conf.j2
    dest: /etc/nftables.d/inet/input/52-buildbot.conf
    owner: root
    group: root
    mode: '0644'

