---
ssh_port: 4242
domains:
  - benwolsieffer.com
  - raspi2.nsupdate.info
  - ben.nsupdate.info
  - hacker-hats.nsupdate.info
  - gameadmin.nsupdate.info
  - raspi2.mooo.com
ip: 192.168.1.2
common_host_users:
  ben:
    groups: [wheel, libvirt]

dnsupdate_secret_keys: [Cg9QbPWQCL, UzZAWg2RW6, J6ewzaDWcQ, 88reQwqPHy, nZWNMMPyya]
dnsupdate_service_file: "templates/{{ inventory_hostname }}/etc/dnsupdate.services.conf.j2"

nginx_worker_processes: 4

docker_dns: [172.17.0.1]
