- name: pacman | install telegraf
  pacman: state=present name=telegraf
  
- name: telegraf | config file
  template: 
    src: etc/telegraf/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'

- name: systemd | enable telegraf
  service:
    name: telegraf
    state: started
    enabled: true
